# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
      - run: sudo apt-get install xvfb
      - run: Xvfb :99 &
      - run: export DISPLAY=:99
      - run: ./gradlew build
      - name: cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1
      - name: junit result
        uses: mikepenz/action-junit-report@v3.6.1
        if: always() # always run even if the previous step fails
        with:
          report_paths: '*/build/test-results/test/TEST-*.xml'